<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr Luke C Pilling">
<meta name="dcterms.date" content="2026-01-23">

<title>Introduction to Epidemiology in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Introduction to Epidemiology in R</h1>
            <p class="subtitle lead">Using simulated UK Biobank data</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Dr Luke C Pilling <a href="mailto:L.Pilling@exeter.ac.uk" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2026-01-23</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">2</span> Setup</a>
  <ul class="collapse">
  <li><a href="#r" id="toc-r" class="nav-link" data-scroll-target="#r"><span class="header-section-number">2.1</span> R</a></li>
  <li><a href="#rstudio" id="toc-rstudio" class="nav-link" data-scroll-target="#rstudio"><span class="header-section-number">2.2</span> RStudio</a></li>
  <li><a href="#tidyverse" id="toc-tidyverse" class="nav-link" data-scroll-target="#tidyverse"><span class="header-section-number">2.3</span> tidyverse</a></li>
  </ul></li>
  <li><a href="#data-loading-and-inspection" id="toc-data-loading-and-inspection" class="nav-link" data-scroll-target="#data-loading-and-inspection"><span class="header-section-number">3</span> Data Loading and Inspection</a>
  <ul class="collapse">
  <li><a href="#load-the-uk-biobank-baseline-assessment-data" id="toc-load-the-uk-biobank-baseline-assessment-data" class="nav-link" data-scroll-target="#load-the-uk-biobank-baseline-assessment-data"><span class="header-section-number">3.1</span> Load the UK Biobank Baseline Assessment Data</a></li>
  <li><a href="#inspecting-the-data" id="toc-inspecting-the-data" class="nav-link" data-scroll-target="#inspecting-the-data"><span class="header-section-number">3.2</span> Inspecting the Data</a></li>
  </ul></li>
  <li><a href="#univariate-summary-and-visualisation" id="toc-univariate-summary-and-visualisation" class="nav-link" data-scroll-target="#univariate-summary-and-visualisation"><span class="header-section-number">4</span> Univariate Summary and Visualisation</a>
  <ul class="collapse">
  <li><a href="#summary-information" id="toc-summary-information" class="nav-link" data-scroll-target="#summary-information"><span class="header-section-number">4.1</span> Summary Information</a></li>
  <li><a href="#tabulate" id="toc-tabulate" class="nav-link" data-scroll-target="#tabulate"><span class="header-section-number">4.2</span> Tabulate</a></li>
  <li><a href="#visualisation" id="toc-visualisation" class="nav-link" data-scroll-target="#visualisation"><span class="header-section-number">4.3</span> Visualisation</a></li>
  </ul></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="header-section-number">5</span> Linear Regression</a>
  <ul class="collapse">
  <li><a href="#linear-regression-model" id="toc-linear-regression-model" class="nav-link" data-scroll-target="#linear-regression-model"><span class="header-section-number">5.1</span> Linear Regression Model</a></li>
  <li><a href="#linear-regression-model-with-covariates" id="toc-linear-regression-model-with-covariates" class="nav-link" data-scroll-target="#linear-regression-model-with-covariates"><span class="header-section-number">5.2</span> Linear Regression Model with Covariates</a></li>
  <li><a href="#confidence-intervals-ci" id="toc-confidence-intervals-ci" class="nav-link" data-scroll-target="#confidence-intervals-ci"><span class="header-section-number">5.3</span> Confidence Intervals (CI)</a></li>
  </ul></li>
  <li><a href="#creating-a-new-binary-variable" id="toc-creating-a-new-binary-variable" class="nav-link" data-scroll-target="#creating-a-new-binary-variable"><span class="header-section-number">6</span> Creating a new binary variable</a>
  <ul class="collapse">
  <li><a href="#identifying-obese-participants" id="toc-identifying-obese-participants" class="nav-link" data-scroll-target="#identifying-obese-participants"><span class="header-section-number">6.1</span> Identifying “Obese” Participants</a></li>
  <li><a href="#comparing-mean-hba1c" id="toc-comparing-mean-hba1c" class="nav-link" data-scroll-target="#comparing-mean-hba1c"><span class="header-section-number">6.2</span> Comparing Mean HbA1c</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">7</span> Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#logistic-regression-model" id="toc-logistic-regression-model" class="nav-link" data-scroll-target="#logistic-regression-model"><span class="header-section-number">7.1</span> Logistic Regression Model</a></li>
  </ul></li>
  <li><a href="#another-example-of-confounding" id="toc-another-example-of-confounding" class="nav-link" data-scroll-target="#another-example-of-confounding"><span class="header-section-number">8</span> Another Example of Confounding</a></li>
  <li><a href="#hypothesis-testing-t2d-and-hba1c" id="toc-hypothesis-testing-t2d-and-hba1c" class="nav-link" data-scroll-target="#hypothesis-testing-t2d-and-hba1c"><span class="header-section-number">9</span> Hypothesis Testing: T2D and HbA1c</a>
  <ul class="collapse">
  <li><a href="#visualisation-1" id="toc-visualisation-1" class="nav-link" data-scroll-target="#visualisation-1"><span class="header-section-number">9.1</span> Visualisation</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">10</span> Summary</a>
  <ul class="collapse">
  <li><a href="#bonus-tasks" id="toc-bonus-tasks" class="nav-link" data-scroll-target="#bonus-tasks"><span class="header-section-number">10.1</span> Bonus tasks</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>This workshop introduces fundamental concepts in epidemiology and statistical analysis using R, focused on health data science. You will learn how to load a text file into R—a commonly used, open source, highly versatile data science program—and perform introductory epidemiological analyses. You will learn how to perform and interpret regression models to estimate associations, including adjusting for confounders.</p>
<p>We’ll use data similar to the UK Biobank, a large 500,000-person cohort that has transformed health data science in recent years (<a href="https://www.ukbiobank.ac.uk/">www.ukbiobank.ac.uk</a>). The scale and depth of the data—including genetics, health records, and deep phenotyping—having provided many insights into mechanisms and predictors of health outcomes. The data is synthetic to protect participant anonymity, though it is designed to resemble real UK Biobank data.</p>
<p>You can find a free “R for Data Science” online book (<a href="https://r4ds.hadley.nz/" class="uri">https://r4ds.hadley.nz/</a>) on how to do data science with R—from the introductory to the advanced.</p>
<p>You can find a free “Epidemiology for the uninitiated” online book (<a href="https://www.bmj.com/about-bmj/resources-readers/publications/epidemiology-uninitiated">www.bmj.com/about-bmj/resources-readers/publications/epidemiology-uninitiated</a>, which includes definitions, study design, sources of bias, and more.</p>
</section>
<section id="setup" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Setup</h1>
<section id="r" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="r"><span class="header-section-number">2.1</span> R</h2>
<p>R is a free, open-source environment for statistical computing, data analysis, and graphics, popular in academia and industry for its powerful tools, extensive packages, and data visualization capabilities.</p>
<p>To install R visit the <a href="https://www.r-project.org/">R Project for Statistical Computing</a> website.</p>
</section>
<section id="rstudio" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="rstudio"><span class="header-section-number">2.2</span> RStudio</h2>
<p>R is a command line tool without a graphical interface. If you wish to use one, I recommend RStudio. It is a desktop environment that allows you to edit and run scripts, see your loaded objects, access the R help manuals, and more, in one environment.</p>
<p>To install RStudio visit the <a href="https://posit.co/download/rstudio-desktop/">posit.co</a> website.</p>
</section>
<section id="tidyverse" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="tidyverse"><span class="header-section-number">2.3</span> tidyverse</h2>
<p>We’ll use functions from the {<a href="https://tidyverse.org/">tidyverse</a>} suite of packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures, providing a comprehensive set of tools for data manipulation, analysis, and visualisation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the {tidyverse} library (if not already installed) </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span> <span class="st">"tidyverse"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()) <span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the {tidyverse} library so the functions are available.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="data-loading-and-inspection" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Loading and Inspection</h1>
<p>This initial step is crucial to ensure the data is imported correctly and that we understand its structure.</p>
<section id="load-the-uk-biobank-baseline-assessment-data" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="load-the-uk-biobank-baseline-assessment-data"><span class="header-section-number">3.1</span> Load the UK Biobank Baseline Assessment Data</h2>
<p>This is a simulated dataset designed to look like the real UK Biobank data (data types, ranges, and approximate correlation structure), but is synthetic to preserve participant anonymity.</p>
<p>You can download the data to your local machine from here <a href="https://lcpilling.github.io/ukb_intro/ukb_baseline.tsv.gz"><code>lcpilling.github.io/ukb_intro/ukb_baseline.tsv.gz</code></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># update path to stored location of the data file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ukb <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"ukb_baseline.tsv.gz"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># or load directly from the internet</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#ukb &lt;- read_tsv("https://lcpilling.github.io/ukb_intro/ukb_baseline.tsv.gz")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="inspecting-the-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="inspecting-the-data"><span class="header-section-number">3.2</span> Inspecting the Data</h2>
<p>We inspect the data’s dimensions, preview the first few rows, and check the variable types—these are shown at the top of the preview table (<code>chr</code>=character string, <code>dbl</code>=numeric).</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check dimensions (rows and columns)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ukb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 500000     13</code></pre>
</div>
</details>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first 6 rows</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ukb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  eid     assessment_date   age   sex   bmi current_smoker   ldl hba1c systolic_bp chd_prevalent chd_incident
  &lt;chr&gt;   &lt;date&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;
1 x100001 2010-07-28         61     1  28.4              0  3.55  43.3        192.             0            1
2 x100002 2010-09-07         51     0  28.0              0  3.05  33.4        143.             0            0
3 x100003 2007-06-07         49     1  29.3              0  3.72  35.6        128.             0            0
4 x100004 2010-02-24         51     1  24.8              0  2.72  34.8        152.             0            0
5 x100005 2009-03-17         57     1  31.3              0  3.34  37.3        162.             0            0
6 x100006 2008-08-05         42     0  33.9              0  3.85  30.1        156.             0            0
  t2d_prevalent t2d_incident
          &lt;dbl&gt;        &lt;dbl&gt;
1             0            0
2             0            0
3             0            0
4             0            0
5             0            1
6             0            0</code></pre>
</div>
</details>
</div>
</section>
</section>
<section id="univariate-summary-and-visualisation" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Univariate Summary and Visualisation</h1>
<p>We’ll focus on some key variables in this tutorial: age, sex, bmi (Body Mass Index), and hba1c (HbA1c, Glycated hemoglobin).</p>
<p>Feel free to explore the others as you go along.</p>
<section id="summary-information" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="summary-information"><span class="header-section-number">4.1</span> Summary Information</h2>
<p>Get summary of numeric variables.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ukb <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, sex, bmi, hba1c) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>      age             sex              bmi            hba1c      
 Min.   :40.00   Min.   :0.0000   Min.   :11.36   Min.   :12.40  
 1st Qu.:49.00   1st Qu.:0.0000   1st Qu.:23.90   1st Qu.:31.86  
 Median :56.00   Median :0.0000   Median :26.86   Median :35.90  
 Mean   :55.45   Mean   :0.4592   Mean   :27.25   Mean   :36.31  
 3rd Qu.:62.00   3rd Qu.:1.0000   3rd Qu.:30.16   3rd Qu.:40.32  
 Max.   :69.00   Max.   :1.0000   Max.   :61.96   Max.   :76.07  
                                  NA's   :12576                  </code></pre>
</div>
</details>
</div>
<p>Note that we are used the <code>|&gt;</code> “pipe operator” to pipe the output of one function to the next, rather than using nested function calls.</p>
<p>We “selected” the variables we wanted from the dataset <code>ukb</code> and passed them to be summarized.</p>
<p>The equivalent “base R” solution (not using the pipe or the tidyverse <code>select()</code> function) would be:</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ukb[,<span class="fu">c</span>(<span class="st">"age"</span>,<span class="st">"sex"</span>,<span class="st">"bmi"</span>,<span class="st">"hba1c"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>      age             sex              bmi            hba1c      
 Min.   :40.00   Min.   :0.0000   Min.   :11.36   Min.   :12.40  
 1st Qu.:49.00   1st Qu.:0.0000   1st Qu.:23.90   1st Qu.:31.86  
 Median :56.00   Median :0.0000   Median :26.86   Median :35.90  
 Mean   :55.45   Mean   :0.4592   Mean   :27.25   Mean   :36.31  
 3rd Qu.:62.00   3rd Qu.:1.0000   3rd Qu.:30.16   3rd Qu.:40.32  
 Max.   :69.00   Max.   :1.0000   Max.   :61.96   Max.   :76.07  
                                  NA's   :12576                  </code></pre>
</div>
</details>
</div>
<p>Both provided the same output, but the first is much more human readable, so we will follow this format throughout this workshop.</p>
<p><code>summary()</code> has provided us a lot of useful information about the four phenotypes. What can you learn from the above?</p>
</section>
<section id="tabulate" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="tabulate"><span class="header-section-number">4.2</span> Tabulate</h2>
<p>Categorical variables such as “sex” and “t2d” can be tabulated, which is more informative that the summary above.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ukb<span class="sc">$</span>sex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
270404 229596 </code></pre>
</div>
</details>
</div>
<p>Note that here, we have accessed a single variable in the <code>ukb</code> data frame using the <code>$</code> symbol. This base R option can sometimes be simpler than using <code>select()</code>.</p>
</section>
<section id="visualisation" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="visualisation"><span class="header-section-number">4.3</span> Visualisation</h2>
<p>We use histograms for continuous variables to show the distribution and bar charts for categorical variables.</p>
<p>Here, we will use the tidyverse <code>ggplot()</code> function to specify the data we will use, then specify the plot type (with <code>geom_*</code>) and options. See the “Visualize” section of the <a href="https://r4ds.hadley.nz/visualize.html">R for Data Science</a> book for detail on this versatile gg “grammar of graphics” approach.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Age Histogram</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ukb <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Age by Decade"</span>, <span class="at">x =</span> <span class="st">"Age (Years)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</details>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sex Bar Chart</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ukb <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make a new variable using `mutate()` to pass text labels to ggplot</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Sex)) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Sex"</span>, <span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</details>
</div>
</section>
</section>
<section id="linear-regression" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Linear Regression</h1>
<p>Let’s hypothesise that BMI differs between males and females.</p>
<p>First, we can simply compare the mean BMI between the sexes.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ukb <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_bmi =</span> <span class="fu">mean</span>(bmi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_bmi =</span> <span class="fu">sd</span>(bmi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_group =</span> <span class="fu">n</span>()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
    sex mean_bmi sd_bmi n_group
  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;int&gt;
1     0     26.8   4.72  270404
2     1     27.8   4.70  229596</code></pre>
</div>
</details>
</div>
<p>We see the mean (average) is different, but is this statistically significant? Is it confounded by different ages between the males and females?</p>
<section id="linear-regression-model" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="linear-regression-model"><span class="header-section-number">5.1</span> Linear Regression Model</h2>
<p>We model BMI (Outcome) with a single predictor variable: sex.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Model (lm): BMI ~ Sex</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> sex, <span class="at">data =</span> ukb)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarise the model results</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ sex, data = ukb)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.451  -3.331  -0.391   2.899  34.203 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 26.811282   0.009171 2923.48   &lt;2e-16 ***
sex          0.945650   0.013536   69.86   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.709 on 487422 degrees of freedom
  (12576 observations deleted due to missingness)
Multiple R-squared:  0.009913,  Adjusted R-squared:  0.009911 
F-statistic:  4880 on 1 and 487422 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</details>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><p><strong>Coefficient (Estimate)</strong>: For <strong>sex</strong>, it is the estimated difference in mean <strong>BMI</strong> between that males and females (the reference group).</p></li>
<li><p><strong>P-value (Pr(&gt;|t|))</strong>: If this value is small (e.g., &lt;0.05), we conclude the predictor is statistically significantly associated with the outcome.</p></li>
</ul>
</section>
<section id="linear-regression-model-with-covariates" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="linear-regression-model-with-covariates"><span class="header-section-number">5.2</span> Linear Regression Model with Covariates</h2>
<p>The above model does not account for any additional factors. Yet, <strong>age</strong> is a classic confounder: it is associated with BMI, and in UK Biobank males and females have different mean age at assessment (females slightly younger).</p>
<p>We can add <code>age</code> to the model, to see whether this changes the estimates.</p>
<p>We model BMI (Outcome) as a function of age and sex (Predictors).</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Model (lm): BMI ~ Age + Sex</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>lm_model_adjusted <span class="ot">&lt;-</span> <span class="fu">lm</span>(bmi <span class="sc">~</span> age <span class="sc">+</span> sex, <span class="at">data =</span> ukb)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarise the model results</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model_adjusted)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ age + sex, data = ukb)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.391  -3.328  -0.392   2.893  34.492 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 2.535e+01  4.633e-02  547.24   &lt;2e-16 ***
age         2.648e-02  8.248e-04   32.10   &lt;2e-16 ***
sex         9.232e-01  1.354e-02   68.19   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.704 on 487421 degrees of freedom
  (12576 observations deleted due to missingness)
Multiple R-squared:  0.012, Adjusted R-squared:  0.012 
F-statistic:  2961 on 2 and 487421 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</details>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><strong>Coefficient (Estimate)</strong>: For <strong>age</strong>, this is the estimated change in mean <strong>BMI</strong> for a one-year increase in age, holding sex constant. For <strong>sex</strong>, it is the estimated difference in mean <strong>BMI</strong> between that males and females (the reference group), holding age constant</li>
</ul>
<p><strong>Conclusion:</strong> Males have higher BMI compared to females, in linear regression models adjusted for age. Whilst adjusting for age attenuated the estimate slightly, there is still a highly significant association.</p>
</section>
<section id="confidence-intervals-ci" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="confidence-intervals-ci"><span class="header-section-number">5.3</span> Confidence Intervals (CI)</h2>
<p>The coefficient is the best estimate of the relationship, yet there is uncertainty in the model. The 95% Confidence Intervals are the range of likely values for the true relationship. Put another way, we are 95% sure the true estimate lines between these values.</p>
<p>We can calculate the 95% Confidence Intervals (or CIs) for the coefficients using the Standard Error outputted by the model:</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first extract the model estimates into a data frame</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> lm_model_adjusted <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">coef</span>() <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># add variables for the confidence intervals</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>CI_lower <span class="ot">&lt;-</span> results<span class="sc">$</span>Estimate <span class="sc">-</span> (results<span class="sc">$</span><span class="st">`</span><span class="at">Std. Error</span><span class="st">`</span> <span class="sc">*</span> <span class="fl">1.96</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>CI_upper <span class="ot">&lt;-</span> results<span class="sc">$</span>Estimate <span class="sc">+</span> (results<span class="sc">$</span><span class="st">`</span><span class="at">Std. Error</span><span class="st">`</span> <span class="sc">*</span> <span class="fl">1.96</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate   Std. Error   t value     Pr(&gt;|t|)    CI_lower    CI_upper
(Intercept) 25.35351691 0.0463296218 547.24204  0.00000e+00 25.26271086 25.44432297
age          0.02647586 0.0008248214  32.09890 7.87475e-226  0.02485921  0.02809251
sex          0.92322721 0.0135401175  68.18458  0.00000e+00  0.89668858  0.94976584</code></pre>
</div>
</details>
</div>
<p>Though in the first table we got the central estimate (the coefficient), here we see the range of estimates are we 95% confident the true estimate lies between.</p>
<p>(Note that R rounds values &lt;1*10-324 to 0)</p>
<p><strong>Conclusion:</strong> Males have 0.92 units higher BMI compared to females (95% CI 0.90 to 0.95, p&lt;1*10<sup>-324</sup>), in linear regression models adjusted for age.</p>
</section>
</section>
<section id="creating-a-new-binary-variable" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Creating a new binary variable</h1>
<p>This demonstrates data stratification based on clinical thresholds.</p>
<section id="identifying-obese-participants" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="identifying-obese-participants"><span class="header-section-number">6.1</span> Identifying “Obese” Participants</h2>
<p>We create a new binary variable <code>obese</code> where [1] indicates BMI &gt; 30 kg/m<sup>2</sup> and [0] otherwise.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ukb <span class="ot">&lt;-</span> ukb <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">obese =</span> <span class="fu">if_else</span>(bmi <span class="sc">&gt;</span> <span class="dv">30</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabulate new variable</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ukb<span class="sc">$</span>obese)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
360884 126540 </code></pre>
</div>
</details>
</div>
</section>
<section id="comparing-mean-hba1c" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="comparing-mean-hba1c"><span class="header-section-number">6.2</span> Comparing Mean HbA1c</h2>
<p>We can compare HbA1c (Glycated haemoglobin, a measure of blood glucose) between the obese and non-obese groups.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ukb <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(obese) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_hba1c =</span> <span class="fu">mean</span>(hba1c, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_hba1c =</span> <span class="fu">sd</span>(hba1c, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_group =</span> <span class="fu">n</span>()</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  obese mean_hba1c sd_hba1c n_group
  &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;   &lt;int&gt;
1     0       35.6     6.26  360884
2     1       38.4     6.27  126540
3    NA       36.3     6.34   12576</code></pre>
</div>
</details>
</div>
<p>Note: “NA” means missing. Not all participants will have data on every phenotype. NAs here show the group with HbA1c but not BMI.</p>
</section>
</section>
<section id="logistic-regression" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Logistic Regression</h1>
<p>This introduces modelling a binary outcome, essential for predicting disease risk.</p>
<section id="logistic-regression-model" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="logistic-regression-model"><span class="header-section-number">7.1</span> Logistic Regression Model</h2>
<p>Let’s use our above hypothesis as the example: we hypothesise that HbA1c differs between the obese and non-obese groups.</p>
<p>We model the odds of being obese (Binary Outcome) as a function of age, sex, and hba1c</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generalised Linear Model (glm) with family="binomial"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(obese <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> hba1c,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> ukb,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = obese ~ age + sex + hba1c, family = "binomial", 
    data = ukb)

Coefficients:
              Estimate Std. Error  z value Pr(&gt;|z|)    
(Intercept) -3.5847204  0.0279176 -128.404   &lt;2e-16 ***
age         -0.0009885  0.0004163   -2.374   0.0176 *  
sex          0.2331410  0.0066901   34.849   &lt;2e-16 ***
hba1c        0.0671336  0.0005360  125.240   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 558245  on 487423  degrees of freedom
Residual deviance: 539329  on 487420  degrees of freedom
  (12576 observations deleted due to missingness)
AIC: 539337

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</details>
</div>
<p>The model coefficients are in terms of log-odds. To interpret them as Odds Ratios (OR), we must exponentiate them.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>result2 <span class="ot">&lt;-</span> logistic_model <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">coef</span>() <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>result2<span class="sc">$</span>OR <span class="ot">&lt;-</span> <span class="fu">exp</span>(result2[,<span class="st">"Estimate"</span>])</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>result2<span class="sc">$</span>CI_lower <span class="ot">&lt;-</span> <span class="fu">exp</span>(result2<span class="sc">$</span>Estimate <span class="sc">-</span> (result2<span class="sc">$</span><span class="st">`</span><span class="at">Std. Error</span><span class="st">`</span> <span class="sc">*</span> <span class="fl">1.96</span>))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>result2<span class="sc">$</span>CI_upper <span class="ot">&lt;-</span> <span class="fu">exp</span>(result2<span class="sc">$</span>Estimate <span class="sc">+</span> (result2<span class="sc">$</span><span class="st">`</span><span class="at">Std. Error</span><span class="st">`</span> <span class="sc">*</span> <span class="fl">1.96</span>))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>result2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate   Std. Error     z value      Pr(&gt;|z|)         OR   CI_lower   CI_upper
(Intercept) -3.5847204270 0.0279176194 -128.403514  0.000000e+00 0.02774442 0.02626708 0.02930486
age         -0.0009885032 0.0004163070   -2.374457  1.757476e-02 0.99901199 0.99819716 0.99982747
sex          0.2331409838 0.0066900652   34.848836 4.434073e-266 1.26255947 1.24611219 1.27922383
hba1c        0.0671335561 0.0005360386  125.240144  0.000000e+00 1.06943830 1.06831530 1.07056248</code></pre>
</div>
</details>
</div>
<p><strong>Odds Ratio (OR)</strong>: This represents the factor change in the odds of the outcome (being obese) for a one-unit increase in the predictor. For example, an OR for hba1c of 1.10 means that for every 1 unit increase in HbA1c, the odds of being obese increase by 10%, holding all other factors constant.</p>
<p><strong>Conclusion:</strong> For each unit increase in HbA1c, the odds of being obese increase by 6.9% (OR 1.069, 95% CIs 1.068 to 1.070, p&lt;1*10<sup>-324</sup>), in logistic regression models adjusted for age and sex.</p>
</section>
</section>
<section id="another-example-of-confounding" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Another Example of Confounding</h1>
<p>In this example, we will test the hypothesis that smokers have higher likelihood of having Coronary Heart Disease (CHD).</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ukb<span class="sc">$</span>chd_prevalent)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
438727  24458 </code></pre>
</div>
</details>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression for CHD ~ Smoking</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>chd_unadjusted_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(chd_prevalent <span class="sc">~</span> current_smoker,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">data =</span> ukb,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get and print the unadjusted estimates</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(chd_unadjusted_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>                  Estimate  Std. Error     z value  Pr(&gt;|z|)
(Intercept)    -2.89038961 0.006960765 -415.240208 0.0000000
current_smoker  0.03219289 0.021067964    1.528049 0.1265003</code></pre>
</div>
</details>
</div>
<p>Yes, the current smokers have higher CHD rates. But is this confounded by age? Age is a classic confounder: it may be associated with smoking (smoking rates may differ in older participants) and is a strong independent risk factor for CHD.</p>
<p>We now add age to the model to see how it affects the estimated relationship between smoking and CHD.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression for CHD ~ Smoking + Age</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>chd_adjusted_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(chd_prevalent <span class="sc">~</span> current_smoker <span class="sc">+</span> age,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> ukb,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get and print the unadjusted Odds Ratio for current_smoker</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(chd_adjusted_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>                  Estimate   Std. Error   z value     Pr(&gt;|z|)
(Intercept)    -7.94263669 0.0571785348 -138.9094 0.000000e+00
current_smoker  0.25366921 0.0214564762   11.8225 2.986582e-32
age             0.08688796 0.0009406972   92.3655 0.000000e+00</code></pre>
</div>
</details>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare Odds Ratios:</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str_c</span>(<span class="st">"Unadjusted OR = "</span>, <span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(chd_unadjusted_model)[<span class="st">"current_smoker"</span>]),<span class="dv">2</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Unadjusted OR = 1.03"</code></pre>
</div>
</details>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str_c</span>(<span class="st">"Adjusted OR = "</span>, <span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(chd_adjusted_model)[<span class="st">"current_smoker"</span>]),<span class="dv">2</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Adjusted OR = 1.29"</code></pre>
</div>
</details>
</div>
<p>Curious! The finding that the association between smoking and Coronary Heart Disease (CHD) gets stronger (the Odds Ratio moves further away from 1) after you adjust for age means that age was previously masking or suppressing the true, independent effect of smoking.</p>
<p>Confounding occurs when a third variable (the confounder, Age in this case) is associated with both the exposure (Smoking) and the outcome (CHD), but is not in the causal pathway between them.</p>
<p>For age to be a negative confounder (or suppressor) in the smoking-CHD relationship, two specific associations must be true:</p>
<ul>
<li><p>Age is strongly associated with the Outcome (CHD): This is universally true; older people have a much higher risk of CHD (Positive Association: Age↑ → CHD Risk↑).</p></li>
<li><p>Age is inversely associated with the Exposure (Smoking): This is the key. In our synthetic UK Biobank data, older participants are less likely to be current smokers than younger participants (Age↑ → Smoking↓).</p></li>
</ul>
<p>This part of the workshop is designed to highlight the importance of thinking of the plausibility of results that you see. It is actually true that older UK Biobank participants are less likely to be current smokers (though, they are more likely to be <em>former</em> smokers), or it could have been a data or coding error.</p>
</section>
<section id="hypothesis-testing-t2d-and-hba1c" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Hypothesis Testing: T2D and HbA1c</h1>
<p>Next, we test a direct clinical hypothesis regarding Type 2 Diabetes (t2d) status and HbA1c (a measure of average blood glucose).</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># N UK Biobank participants with type-2 diabetes at baseline</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ukb<span class="sc">$</span>t2d_prevalent)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
446884  16301 </code></pre>
</div>
</details>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression model</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(t2d_prevalent <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> hba1c,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> ukb,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = t2d_prevalent ~ age + sex + hba1c, family = "binomial", 
    data = ukb)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -19.104888   0.113124 -168.88   &lt;2e-16 ***
age           0.045735   0.001270   36.01   &lt;2e-16 ***
sex           0.662573   0.019444   34.08   &lt;2e-16 ***
hba1c         0.304960   0.001769  172.38   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 141137  on 463184  degrees of freedom
Residual deviance:  86075  on 463181  degrees of freedom
  (36815 observations deleted due to missingness)
AIC: 86083

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</details>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(logistic_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age          sex        hba1c 
5.044902e-09 1.046797e+00 1.939777e+00 1.356571e+00 </code></pre>
</div>
</details>
</div>
<p>You should see that all our phenotype included on the “right” of the regression formula are strongly and independently associated with type-2 diabetes status.</p>
<section id="visualisation-1" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="visualisation-1"><span class="header-section-number">9.1</span> Visualisation</h2>
<p>A boxplot is a useful visualisation to see difference in means across groups.</p>
<div class="cell" data-output-fold="true" data-output-summary="View output">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>ukb <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ensure T2D status is labelled clearly on the plot</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">t2d_group =</span> <span class="fu">factor</span>(t2d_prevalent, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Non-Diabetic"</span>, <span class="st">"T2D"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> t2d_group, <span class="at">y =</span> hba1c, <span class="at">fill =</span> t2d_group)) <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"HbA1c Distribution by Type 2 Diabetes Status"</span>,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"T2D Status"</span>,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"HbA1c (mmol/mol)"</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<details><summary>View output</summary>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</details>
</div>
</section>
</section>
<section id="summary" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Summary</h1>
<p>In this workshop you have loaded and inspected a large human cohort, tested hypotheses using regression models, adjusted for potential confounders, and begun to explore methods for visualisation.</p>
<section id="bonus-tasks" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="bonus-tasks"><span class="header-section-number">10.1</span> Bonus tasks</h2>
<p>Repeat the investigations for the “systolic_bp” variable, which corresponds to measured Systolic Blood Pressure.</p>
<p>Try to find out:</p>
<ul>
<li>What is the average (mean) systolic BP? Does the range of values seem realistic?</li>
<li>Does the distribution on the histogram look approximately Gaussian (“normal”)?</li>
<li>Test associations with age and sex. What are the associations?</li>
<li>Create a binary variable “hypertension” where participants with <code>systolic_bp &gt;= 140</code> are defined as cases. How many are there?</li>
<li>What is the association between hypertension and age and sex?</li>
<li>What is the association between hypertension and prevalent Coronary Heart Disease (chd_prevalent)?</li>
</ul>
<p>Explore associations between baseline risk factors and incident disease variables.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>